name: Despertador de Streamlit via Commit

on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas
  workflow_dispatch:      # Para que puedas probarlo con el botón manual

jobs:
  update-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Actualizar archivo de actividad
        run: |
          echo "Último pulso de actividad: $(date)" > keep_alive.txt
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add keep_alive.txt
          git commit -m "Keep-alive: Despertando app (Automático)" || echo "No hay cambios para subir"
          git push
